routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Exports\ProductsExport;
use App\Exports\OrdersExport;
use App\Exports\ProductUnitExport;
use App\Exports\ProductSubCategoryExport;
use Maatwebsite\Excel\Facades\Excel;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',function(){
    return view("site.home");
});
Route::get('/about-us',function(){
    return view("site.about");
});
Route::get('/privacy-policy',function(){
    return view("site.privacy_policy");
});
Route::get('/terms-and-conditions',function(){
    return view("site.terms_and_conditions");
});

Route::get('/login',"Admin\AuthController@loginShow")->name('admin.login')->middleware('guest:admin');
Route::post('/login',"Admin\AuthController@loginPost")->name('admin.login.store');
Route::get('/logout',"Admin\AuthController@logout")->name('admin.logout')->middleware('auth:admin');

Route::middleware('auth:admin')->group(function () {
    
    Route::get('orders',"Admin\OrderController@index")->name('orders.index');
    Route::get('orders/{id}/{notifyId?}',"Admin\OrderController@detail")->name('orders.detail');
    Route::get('home',"Admin\HomeController@index")->name('home');
    Route::post('AjaxCallForAssignRider', 'Admin\OrderController@AjaxCallForAssignRider')->name('AjaxCallForAssignRider');
    Route::get('ajax-notifications', 'Admin\AjaxController@notificationAlert')->name('AjaxNotificationAlert');

    Route::post('/passwordchange','Admin\AuthController@changePassword')->name('change.password');

    //check if user type is equal to admin or not
    Route::middleware('isadmin')->group(function () {
        
        
        Route::resource('productunit',"Admin\ProductUnitController");
        Route::resource('category',"Admin\ProductCategoryController",['except' => ['destroy', 'show']]);
        Route::resource('products',"Admin\ProductsController",['except' => ['destroy', 'show']]);
        Route::resource('riders', "Admin\RiderController");
        Route::resource('customers', "Admin\CustomerController");
        Route::resource('bundles', "Admin\BundleController");

        Route::resource('sub-category', "Admin\ProductSubCategoryController");
        

        Route::post('AjaxCallForBundleProductDelete','Admin\AjaxController@AjaxCallForBundleProductDelete')->name('AjaxCallForBundleProductDelete');
        Route::post('AjaxCallForViewBundle','Admin\AjaxController@AjaxCallForViewBundle')->name('AjaxCallForViewBundle');
        Route::post('AjaxCallForViewProduct','Admin\AjaxController@AjaxCallForViewProduct')->name('AjaxCallForViewProduct');

        
        Route::post('import/products',"Admin\ProductsController@importProducts")->name('import.products');

        Route::get('export/products',function(){
            $filename = "products list ".date('Y_m_d').".xlsx";
            return Excel::download(new ProductsExport, $filename);
        })->name('export.products');
        
        
        Route::get('export/orders',function(){
            $filename = "orders list ".date('Y_m_d').".xlsx";
            return Excel::download(new OrdersExport, $filename);
        })->name('export.orders');

        Route::get('export/product-unit',function(){
            $filename = "product units ".date('Y_m_d').".xlsx";
            return Excel::download(new ProductUnitExport, $filename);
        })->name('export.product-unit');

        Route::get('export/product-subcategory',function(){
            $filename = "product-subcategory ".date('Y_m_d').".xlsx";
            return Excel::download(new ProductSubCategoryExport, $filename);
        })->name('export.product-subcategory');

        Route::get('remove-product-image/{id}','Admin\AjaxController@RemoveProductImage')->name('RemoveProductImage');
        Route::post('add-product-images','Admin\AjaxController@AddProductImages')->name('AddProductImages');
    });
});

app/Models/ProductCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;

class ProductCategory extends Model implements TranslatableContract
{
    use Translatable;
    protected $fillable = ['image_name','active'];
    public $translatedAttributes = ['name'];

    public function getImagePathAttribute()
    {
        return asset("/images/categories/{$this->image_name}");
    }

    public function products()
    {
        return $this->hasMany('App\Models\Product','product_category_id');
    }
}

app/Http/Controllers/Admin/ProductCategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\ProductCategory;
use App\Models\SubCategory;
use Str;
use File;
use Illuminate\Validation\Rule;

class ProductCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = ProductCategory::all();
        return view('admin.productcategory.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.productcategory.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'en_name' => 'required|string|max:255|unique:product_category_translations,name',
            'ur_name' => 'required|string|max:255|unique:product_category_translations,name',
            'image' => 'required|image',
        ]);
        $imageName = Str::random(5).'_'.time().'.'.$request->image->extension();
        $article_data = [
            'en' => [
                'name'       => $request->en_name,
            ],
            'ur' => [
                'name'       => $request->ur_name,
            ],
            "image_name" => $imageName,
            "active" => $request->has('active')?1:0
         ];
         $request->image->move(public_path('/images/categories'), $imageName);
         ProductCategory::create($article_data);
         return redirect()->route('category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = ProductCategory::findOrFail($id);
        return view('admin.productcategory.edit',compact('category')); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'en_name' => 'required|string|max:255|unique:product_category_translations,name,'.$id.',product_category_id',
            'ur_name' => 'required|string|max:255|unique:product_category_translations,name,'.$id.',product_category_id',
            'image' => 'nullable|image',
            ]);
        $category = ProductCategory::findOrFail($id);
        if($request->hasFile('image'))
        {
            File::delete(public_path('/images/categories/'.$category->image_name));
            $imageName = Str::random(5).'_'.time().'.'.$request->image->extension();
            $request->image->move(public_path('/images/categories'), $imageName);
            $category->image_name = $imageName;
        }
        $category->translate('en')->name = $request->en_name;
        $category->translate('ur')->name = $request->ur_name;
        $category->active = $request->has('active')?1:0;
        if(!$request->has('active'))
        {
            if(SubCategory::where("product_category_id",$id)->where('active',1)->exists()){
                return redirect()->back()->withErrors(['active'=>'Can\'t deactive category because sub categories available.']);
            }
        }
        $category->save();
        return redirect()->route('category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/productcategory/create.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card card-primary mt-4">
                <div class="card-header">
                  <h3 class="card-title">Add Product Category</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form action="{{route('category.store')}}" method="post" enctype="multipart/form-data">
                    @csrf
                  <div class="card-body">
                    <img src="" height="150" width="auto" alt="" id="categoryImage" srcset="">
                    <div class="form-group">
                      <label for="en_name">Category Name (English)</label>
                      <input type="text" name="en_name" class="form-control" value="{{old('en_name')}}" id="en_name">
                      @error('en_name')
                          <p class="text-danger text-sm">{{$message}}</p>
                      @enderror
                    </div>
                    <div class="form-group">
                      <label for="ur_name">Category Name (اردو)</label>
                      <input type="text" name="ur_name" class="form-control" value="{{old('ur_name')}}" id="ur_name">
                      @error('ur_name')
                          <p class="text-danger text-sm">{{$message}}</p>
                      @enderror
                    </div>
                    <div class="form-group">
                      <label for="image">Product Category Image</label>
                      <input type="file" class="form-control-file" name="image" id="image" accept="image/*">
                      @error('image')
                          <p class="text-danger text-sm">{{$message}}</p>
                        @enderror
                    </div>
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input" value="1" name="active" id="active" checked>
                        <label class="form-check-label" for="active">Is Active</label>
                      </div>
                  </div>
                  <!-- /.card-body -->
                  <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a href="{{route('category.index')}}" class="btn btn-default">Back</a>
                  </div>
                </form>
              </div>
          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
@endsection
@push('custom-script')
    <script>
      var fileInput = document.querySelector("#image")
      var ImageElement = document.querySelector("#categoryImage")
      
      fileInput.addEventListener("change",function(){
        if (fileInput.files && fileInput.files[0]) {
          var reader = new FileReader();
          reader.onload = function(e) {
            ImageElement.setAttribute("src", e.target.result);
          }
          reader.readAsDataURL(fileInput.files[0]); // convert to base64 string
        }
      })
    </script>
@endpush

resources/views/admin/productcategory/edit.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card card-primary mt-4">
                <div class="card-header">
                  <h3 class="card-title">Edit Product Category</h3>
                </div>

                <!-- /.card-header -->
                <!-- form start -->
                <form action="{{route('category.update',$category->id)}}" method="post" enctype="multipart/form-data">
                    @method('PUT')
                    @csrf
                  <div class="card-body">
                      <img src="{{$category->image_path}}" height="150" width="auto" alt="" id="categoryImage" srcset="">
                    <div class="form-group">
                      <label for="en_name">Category Name (English)</label>
                      <input type="text" name="en_name" class="form-control" value="{{$category->translate('en')->name}}" id="en_name">
                      @error('en_name')
                          <p class="text-danger text-sm">{{$message}}</p>
                      @enderror
                    </div>
                    <div class="form-group">
                      <label for="ur_name">Category Name (اردو)</label>
                      <input type="text" name="ur_name" class="form-control" value="{{$category->translate('ur')->name}}" id="ur_name">
                      @error('ur_name')
                          <p class="text-danger text-sm">{{$message}}</p>
                      @enderror
                    </div>
                    <div class="form-group">
                      <label for="image">Change Category Image</label>
                      <input type="file" class="form-control-file" name="image" id="image" accept="image/*">
                      @error('image')
                          <p class="text-danger text-sm">{{$message}}</p>
                        @enderror
                    </div>
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input" value="1" name="active" id="active" checked>
                        <label class="form-check-label" for="active">Is Active</label>
                      </div>
                      @error('active')
                          <p class="text-danger text-sm">{{$message}}</p>
                      @enderror
                  </div>
                  <!-- /.card-body -->
                  <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Update</button>
                    <a href="{{route('category.index')}}" class="btn btn-default">Back</a>
                  </div>
                </form>
              </div>
          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
@endsection
@push('custom-script')
    <script>
      var fileInput = document.querySelector("#image")
      var ImageElement = document.querySelector("#categoryImage")
      
      fileInput.addEventListener("change",function(){
        if (fileInput.files && fileInput.files[0]) {
          var reader = new FileReader();
          reader.onload = function(e) {
            ImageElement.setAttribute("src", e.target.result);
          }
          reader.readAsDataURL(fileInput.files[0]); // convert to base64 string
        }
      })
    </script>
@endpush

resources/views/admin/productcategory/index.blade.php
@extends('admin.layouts.app')
@push('custom-css')
<link rel="stylesheet" href="{{asset('backend/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{asset('backend/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{asset('backend/plugins/datatables-buttons/css/buttons.bootstrap4.min.css')}}">
@endpush
@section('content')

<div class="content-wrapper">
    <section class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-12">
                    <div class="card mt-3">
                        <div class="card-header">
                            {{-- <h3 class="card-title">DataTable with default features</h3> --}}
                            <div class="row mb-2">
                                <div class="col-sm-12">
                                    <h3>Product Categories 
										{{-- <a href="{{route('export.orders')}}" class="btn btn-info btn-sm float-right">Export</a> --}}
											<a href="{{route('category.create')}}" class="btn btn-primary mb-3 float-right">Add Product Category</a>
									</h3>
                                </div>
                            </div>
                        </div>
                        <div class=" ">
                            <br>
                            <!-- Nav tabs -->
                            <ul class="nav nav-tabs nav-justified">
                                <li class="nav-item">
                                    <a class="nav-link active" data-toggle="tab" href="#menu1">Active</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" data-toggle="tab" href="#menu2">Deactive</a>
                                </li>
                                
                            </ul>

                            <!-- Tab panes -->
                            <div class="tab-content">
                                <div id="menu1" class="tab-pane active"><br>

                                    <div class="card-body">
                                        <table class="table table-bordered table-striped" id="data-table">
											<thead>
												<tr>
													<th>Sr.No</th>
													<th>Name (English)</th>
													<th>Name (اردو)</th>
													<th>Image</th>
													<th>Active</th>
													<th></th>
												</tr>
											</thead>
											<tbody>
												@php
													$count = 0;
												@endphp
												@foreach ($categories as $key => $item)
												
												@if ($item->active == 1)
												<tr>
													<td>{{++$count}}</td>
													<td>{{$item->translate('en')->name}}</td>
													<td>{{$item->translate('ur')->name}}</td>
													<td><img src="{{$item->image_path}}" height="60" width="auto" alt="" srcset="">
													</td>
													<td>{{$item->active == 1?'active':'deactive'}}</td>
													<td><a href="{{route('category.edit',$item->id)}}"
															class="btn btn-primary btn-sm"><i class="fa fa-edit"></i></a></td>
												</tr>
												@endif
												
												@endforeach
											</tbody>
										</table>
                                        
                                    </div>
                                </div>
                                <div id="menu2" class="tab-pane fade"><br>
                                    <div class="card-body">
										<table class="table table-bordered table-striped" id="data-table1">
											<thead>
												<tr>
													<th>Sr.No</th>
													<th>Name (English)</th>
													<th>Name (اردو)</th>
													<th>Image</th>
													<th>Active</th>
													<th></th>
												</tr>
											</thead>
											<tbody>
												@php
													$count1 = 0;
												@endphp
												@foreach ($categories as $key => $item)
												@if ($item->active != 1)
												<tr>
													<td>{{++$count1}}</td>
													<td>{{$item->translate('en')->name}}</td>
													<td>{{$item->translate('ur')->name}}</td>
													<td><img src="{{$item->image_path}}" height="60" width="auto" alt="" srcset="">
													</td>
													<td>{{$item->active == 1?'active':'deactive'}}</td>
													<td><a href="{{route('category.edit',$item->id)}}"
															class="btn btn-primary btn-sm"><i class="fa fa-edit"></i></a></td>
												</tr>
												@endif
												
												@endforeach
											</tbody>
										</table>
                                        
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{{-- <div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card card-primary mt-4">
                        <div class="card-header">
                            <h3 class="card-title">Product Categories</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <a href="{{route('category.create')}}" class="btn btn-primary mb-3">Add Product Category</a>
                            <table class="table table-bordered table-striped" id="data-table">
                                <thead>
                                    <tr>
                                        <th>Sr.No</th>
                                        <th>Name (English)</th>
                                        <th>Name (اردو)</th>
                                        <th>Image</th>
                                        <th>Active</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($categories as $key => $item)
                                    <tr>
                                        <td>{{++$key}}</td>
                                        <td>{{$item->translate('en')->name}}</td>
                                        <td>{{$item->translate('ur')->name}}</td>
                                        <td><img src="{{$item->image_path}}" height="60" width="auto" alt="" srcset="">
                                        </td>
                                        <td>{{$item->active == 1?'active':'deactive'}}</td>
                                        <td><a href="{{route('category.edit',$item->id)}}"
                                                class="btn btn-primary btn-sm"><i class="fa fa-edit"></i></a></td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div> --}}
@endsection
@push('custom-script')
<script src="{{asset('backend/plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('backend/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{asset('backend/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{asset('backend/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
<script>
    $(function () {
        $("#data-table").DataTable();
        $("#data-table1").DataTable();

    });

</script>
@endpush