routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Exports\ProductsExport;
use App\Exports\OrdersExport;
use App\Exports\ProductUnitExport;
use App\Exports\ProductSubCategoryExport;
use Maatwebsite\Excel\Facades\Excel;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',function(){
    return view("site.home");
});
Route::get('/about-us',function(){
    return view("site.about");
});
Route::get('/privacy-policy',function(){
    return view("site.privacy_policy");
});
Route::get('/terms-and-conditions',function(){
    return view("site.terms_and_conditions");
});

Route::get('/login',"Admin\AuthController@loginShow")->name('admin.login')->middleware('guest:admin');
Route::post('/login',"Admin\AuthController@loginPost")->name('admin.login.store');
Route::get('/logout',"Admin\AuthController@logout")->name('admin.logout')->middleware('auth:admin');

Route::middleware('auth:admin')->group(function () {
    
    Route::get('orders',"Admin\OrderController@index")->name('orders.index');
    Route::get('orders/{id}/{notifyId?}',"Admin\OrderController@detail")->name('orders.detail');
    Route::get('home',"Admin\HomeController@index")->name('home');
    Route::post('AjaxCallForAssignRider', 'Admin\OrderController@AjaxCallForAssignRider')->name('AjaxCallForAssignRider');
    Route::get('ajax-notifications', 'Admin\AjaxController@notificationAlert')->name('AjaxNotificationAlert');

    Route::post('/passwordchange','Admin\AuthController@changePassword')->name('change.password');

    //check if user type is equal to admin or not
    Route::middleware('isadmin')->group(function () {
        
        
        Route::resource('productunit',"Admin\ProductUnitController");
        Route::resource('category',"Admin\ProductCategoryController",['except' => ['destroy', 'show']]);
        Route::resource('products',"Admin\ProductsController",['except' => ['destroy', 'show']]);
        Route::resource('riders', "Admin\RiderController");
        Route::resource('customers', "Admin\CustomerController");
        Route::resource('bundles', "Admin\BundleController");

        Route::resource('sub-category', "Admin\ProductSubCategoryController");
        

        Route::post('AjaxCallForBundleProductDelete','Admin\AjaxController@AjaxCallForBundleProductDelete')->name('AjaxCallForBundleProductDelete');
        Route::post('AjaxCallForViewBundle','Admin\AjaxController@AjaxCallForViewBundle')->name('AjaxCallForViewBundle');
        Route::post('AjaxCallForViewProduct','Admin\AjaxController@AjaxCallForViewProduct')->name('AjaxCallForViewProduct');

        
        Route::post('import/products',"Admin\ProductsController@importProducts")->name('import.products');

        Route::get('export/products',function(){
            $filename = "products list ".date('Y_m_d').".xlsx";
            return Excel::download(new ProductsExport, $filename);
        })->name('export.products');
        
        
        Route::get('export/orders',function(){
            $filename = "orders list ".date('Y_m_d').".xlsx";
            return Excel::download(new OrdersExport, $filename);
        })->name('export.orders');

        Route::get('export/product-unit',function(){
            $filename = "product units ".date('Y_m_d').".xlsx";
            return Excel::download(new ProductUnitExport, $filename);
        })->name('export.product-unit');

        Route::get('export/product-subcategory',function(){
            $filename = "product-subcategory ".date('Y_m_d').".xlsx";
            return Excel::download(new ProductSubCategoryExport, $filename);
        })->name('export.product-subcategory');

        Route::get('remove-product-image/{id}','Admin\AjaxController@RemoveProductImage')->name('RemoveProductImage');
        Route::post('add-product-images','Admin\AjaxController@AddProductImages')->name('AddProductImages');
    });
});

app/Http/Controllers/Admin/ProductSubCategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\ProductCategory;
use App\Models\SubCategory;
use App\Models\Product;

class ProductSubCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $ProductSubCategory = SubCategory::all();
        return view('admin.productSubCategory.index',compact('ProductSubCategory'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $ProductCategory = ProductCategory::where('active',1)->get();
        return view('admin.productSubCategory.create',compact('ProductCategory'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request);

        $request->validate([
            'product_category'  => 'required',
            'sub_category_en'   => 'required|string|max:255|unique:sub_category_translations,subcategory',
            'sub_category_ur'   => 'required|string|max:255|unique:sub_category_translations,subcategory',
        ],[
            'product_category.required' => 'This field is required.',
            'sub_category_en.required'  => 'This field is required.',
            'sub_category_ur.required'  => 'This field is required.'
        ]);

        $sub_category_data = [
            'en' => [
                'subcategory'       => $request->sub_category_en,
            ],
            'ur' => [
                'subcategory'       => $request->sub_category_ur,
            ],
            "product_category_id"   => $request->product_category,
            "active"                => $request->has('is_active')?1:0,
        ];
        SubCategory::create($sub_category_data);
        return redirect()->route('sub-category.index')->withMessage('Product Sub Category Created Successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $ProductSubCategory = SubCategory::find($id);
        $ProductCategory = ProductCategory::all();
        return view('admin.productSubCategory.edit',compact('ProductSubCategory','ProductCategory'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'product_category'  => 'required',
            'sub_category_en'   => 'required|string|max:255|unique:sub_category_translations,subcategory,'.$id.',sub_category_id',
            'sub_category_ur'   => 'required|string|max:255|unique:sub_category_translations,subcategory,'.$id.',sub_category_id',
        ],[
            'product_category.required' => 'This field is required.',
            'sub_category_en.required'  => 'This field is required.',
            'sub_category_ur.required'  => 'This field is required.'
        ]);

        $SubCategory                                = SubCategory::findOrFail($id);
        $SubCategory->translate('en')->subcategory  = $request->sub_category_en;
        $SubCategory->translate('ur')->subcategory  = $request->sub_category_ur;
        $SubCategory->product_category_id           = $request->product_category;
        $SubCategory->active                        = $request->has('is_active')?1:0;
        if(!$request->has('active'))
        {
            if(Product::where("sub_category_id",$id)->where('active',1)->exists()){
                return redirect()->back()->withErrors(['active'=>'Can\'t deactive sub category because products available.']);
            }
        }
        $SubCategory->save();

        return redirect()->route('sub-category.index')->withMessage('Product Sub Category Updated Successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/productSubCategory/create.blade.php
@extends('admin.layouts.app')


@section('content')

<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Add Sub Category</h1>
                </div>
                <div class="col-sm-6">

                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- jquery validation -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Enter Sub Category</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form id="quickForm" method="POST" action="{{route('sub-category.store')}}">
                            @csrf
                            <div class="card-body">
                                <div class="row">
                                    <div class="form-group col-md-6 @error('product_category') is-invalid @enderror">
                                        <label for="exampleInputEmail1">Category</label>
                                        <select name="product_category" id="" class="form-control">
                                            <option selected disabled>Select Option</option>
                                            @foreach ($ProductCategory as $item)
                                            <option value="{{$item->id}}"
                                                {{(old('product_category')!=null)? (old('product_category')==$item->id? 'selected':''):''}}>
                                                {{$item->translate('en')->name}}</option>
                                            @endforeach
                                        </select>
                                        @error('product_category')
                                        <p class="text-danger text-sm">{{$message}}</p>
                                        @enderror
                                    </div>

                                    <div class="form-group col-md-6">
                                    </div>
                                    <div class="form-group col-md-6 @error('sub_category_en') is-invalid @enderror">
                                        <label for="">Sub Category (English)</label>
                                        <input type="text" name="sub_category_en" class="form-control" placeholder="Enter Sub Category (English)" value="{{old('sub_category_en')}}">
                                        @error('sub_category_en')
                                        <p class="text-danger text-sm">{{$message}}</p>
                                        @enderror
                                    </div>
                                    <div class="form-group col-md-6 @error('sub_category_ur') is-invalid @enderror">
                                        <label for="">Sub Category (اردو)</label>
                                        <input type="text" name="sub_category_ur" class="form-control" placeholder="Enter Sub Category (اردو)" value="{{old('sub_category_ur')}}">
                                        @error('sub_category_ur')
                                        <p class="text-danger text-sm">{{$message}}</p>
                                        @enderror
                                    </div>
                                    <div class="form-group col-md-12">
                                        <div class="form-check ">
                                            <input type="checkbox" name="is_active" id="is_active" class="form-check-input" value="{{old('is_active')!=null? old('is_active'):1}}"  {{(old('is_active')!=null)? (old('is_active')==1? 'checked':''):'checked'}} > Is Active
                                                {{-- @error('address')
                                                    <p class="text-danger text-sm">{{$message}}</p>
                                                @enderror --}}
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary" id="submit_btn">Submit</button>
                                <a href="{{route('sub-category.index')}}" class="btn btn-default">Back</a>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->
                </div>

            </div>

        </div>
    </section>
</div>
@endsection

resources/views/admin/productSubCategory/edit.blade.php
@extends('admin.layouts.app')


@section('content')

<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Add Sub Category</h1>
                </div>
                <div class="col-sm-6">

                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- jquery validation -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Enter Sub Category</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form id="quickForm" method="POST" action="{{route('sub-category.update',$ProductSubCategory->id)}}">
                            @method('PUT')
                            @csrf
                            <div class="card-body">
                                <div class="row">
                                    <div class="form-group col-md-6 @error('product_category') is-invalid @enderror">
                                        <label for="exampleInputEmail1">Category</label>
                                        <select name="product_category" id="" class="form-control">
                                            <option selected disabled>Select Option</option>
                                            @foreach ($ProductCategory as $item)
                                            <option value="{{$item->id}}"
                                                {{(old('product_category')!=null)? (old('product_category')==$item->id? 'selected':''):($ProductSubCategory->product_category_id==$item->id? 'selected':'')}}>
                                                {{$item->translate('en')->name}}</option>
                                            @endforeach
                                        </select>
                                        @error('product_category')
                                        <p class="text-danger text-sm">{{$message}}</p>
                                        @enderror
                                    </div>

                                    <div class="form-group col-md-6">
                                    </div>
                                    <div class="form-group col-md-6 @error('sub_category_en') is-invalid @enderror">
                                        <label for="">Sub Category (English)</label>
                                        <input type="text" name="sub_category_en" class="form-control" placeholder="Enter Sub Category (English)" value="{{(old('sub_category_en')!=null)? old('sub_category_en'):$ProductSubCategory->translate('en')->subcategory }}">
                                        @error('sub_category_en')
                                        <p class="text-danger text-sm">{{$message}}</p>
                                        @enderror
                                    </div>
                                    <div class="form-group col-md-6 @error('sub_category_ur') is-invalid @enderror">
                                        <label for="">Sub Category (اردو)</label>
                                        <input type="text" name="sub_category_ur" class="form-control" placeholder="Enter Sub Category (اردو)" value="{{(old('sub_category_ur')!=null)? old('sub_category_ur'):$ProductSubCategory->translate('ur')->subcategory}}">
                                        @error('sub_category_ur')
                                        <p class="text-danger text-sm">{{$message}}</p>
                                        @enderror
                                    </div>
                                    <div class="form-group col-md-12">
                                        <div class="form-check ">
                                            <input type="checkbox" name="is_active" id="is_active" class="form-check-input" value="{{old('is_active')!=null? old('is_active'):1}}"  {{(old('is_active')!=null)? (old('is_active')==1? 'checked':''):(($ProductSubCategory->active==1)?'checked':'')}} > Is Active
                                        </div>
                                        @error('active')
                                            <p class="text-danger text-sm">{{$message}}</p>
                                        @enderror
                                    </div>
                                </div>

                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary" id="submit_btn">Submit</button>
                                <a href="{{route('sub-category.index')}}" class="btn btn-default">Back</a>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->
                </div>

            </div>

        </div>
    </section>
</div>
@endsection

resources/views/admin/productSubCategory/index.blade.php
@extends('admin.layouts.app')


@push('custom-css')

<!-- DataTables -->
<link rel="stylesheet" href="{{asset('backend/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{asset('backend/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{asset('backend/plugins/datatables-buttons/css/buttons.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{asset('backend/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css')}}">
<link rel="stylesheet" href="{{asset('backend/plugins/toastr/toastr.min.css')}}">

    
@endpush

@section('content')

<div class="content-wrapper">
    <section class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-12">
                    <div class="card mt-3">
                        <div class="card-header">
                            {{-- <h3 class="card-title">DataTable with default features</h3> --}}
                            <div class="row mb-2">
                                <div class="col-sm-12">
                                    <h3>View all Product Sub Category 
                                            <a href="{{route('sub-category.create')}}" class="btn btn-success" style="float:right" >Add Product Sub Category</a>
                                            <a href="{{route('export.product-subcategory')}}" class="btn btn-primary mr-2" style="float:right" >Export Sub Category</a>
                                        </h3>
                                </div>
                            </div>
                        </div>
                        <div class=" ">
                            
                            <br>
                            <!-- Nav tabs -->
                            <ul class="nav nav-tabs nav-justified">
                                <li class="nav-item">
                                    <a class="nav-link active" data-toggle="tab" href="#menu1">Active</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" data-toggle="tab" href="#menu2">Deactive</a>
                                </li>
                                
                            </ul>

                            <!-- Tab panes -->
                            <div class="tab-content">
                                <div id="menu1" class="tab-pane active"><br>

                                    <div class="card-body">
                                        <div id="msg"></div>
                                        <table class="table table-bordered table-striped" id="example1">
                                            <thead>
                                                <tr>
                                                    <th>S. No#</th>
                                                    <th>Product Category</th>
                                                    <th>Product Sub Category (English)</th>
                                                    <th>Product Sub Category (اردو)</th>
                                                    <th>Active</th>
                                                    <th>Action</th> 
                                                </tr>
                                            </thead>
                                            <tbody>
                                                
                                                @php
                                                $count = 0;
                                                @endphp
                                                @foreach ($ProductSubCategory as $item)
                                                @if ($item->active == 1)
                                                <tr>
                                                    <td>{{++$count}}</td>
                                                    <td>{{$item->productCategory->translate('en')->name}}</td>
                                                    <td>{{$item->translate('en')->subcategory}}</td>
                                                    <td>{{$item->translate('ur')->subcategory}}</td>
                                                    <td>{{($item->active==1)? 'Active':'Deactive'}}</td>
                                                    <td>
                                                        <a href="{{route('sub-category.edit',$item->id)}}" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i></a>
                                                    </td>
                                                </tr>
                                                @endif
                                                @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div id="menu2" class="tab-pane fade"><br>
                                    <div class="card-body">
                                        <div id="msg"></div>
                                        <table class="table table-bordered table-striped" id="example2">
                                            <thead>
                                                <tr>
                                                    <th>S. No#</th>
                                                    <th>Product Category</th>
                                                    <th>Product Sub Category (English)</th>
                                                    <th>Product Sub Category (اردو)</th>
                                                    <th>Active</th>
                                                    <th>Action</th> 
                                                </tr>
                                            </thead>
                                            <tbody>
                                                
                                                @php
                                                $count1 = 0;
                                                @endphp
                                                @foreach ($ProductSubCategory as $item)
                                                @if ($item->active != 1)
                                                <tr>
                                                    <td>{{++$count1}}</td>
                                                    <td>{{$item->productCategory->translate('en')->name}}</td>
                                                    <td>{{$item->translate('en')->subcategory}}</td>
                                                    <td>{{$item->translate('ur')->subcategory}}</td>
                                                    <td>{{($item->active==1)? 'Active':'Deactive'}}</td>
                                                    <td>
                                                        <a href="{{route('sub-category.edit',$item->id)}}" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i></a>
                                                    </td>
                                                </tr>
                                                @endif
                                                @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                             
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

{{-- <div class="content-wrapper">

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            
            <div class="row">

                @if (Session::has('message'))
                <div class="col-12 mt-3">
                    <div class="alert alert-info alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        {{Session::get('message')}}
                    </div>
                </div>
                @endif

                <div class="col-12">
                    <div class="card mt-3">
                        <div class="card-header">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h3>Product Sub Category</h3>
                                </div>
                                <div class="col-sm-6">
                                    <a href="{{route('sub-category.create')}}" class="btn btn-success" style="float:right" >Add Product Sub Category</a>
                                </div>
                                
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>S. No#</th>
                                        <th>Product Category</th>
                                        <th>Product Sub Category (English)</th>
                                        <th>Product Sub Category (اردو)</th>
                                        <th>Active</th>
                                        <th>Action</th> 
                                    </tr>
                                </thead>
                                <tbody>
                                    @php
                                        $i = 1
                                    @endphp

                                    @foreach ($ProductSubCategory as $item)
                                    <tr>
                                        <td>{{$i++}}</td>
                                        <td>{{$item->productCategory->translate('en')->name}}</td>
                                        <td>{{$item->translate('en')->subcategory}}</td>
                                        <td>{{$item->translate('ur')->subcategory}}</td>
                                        <td>{{($item->active==1)? 'Active':'Deactive'}}</td>
                                        <td>
                                            <a href="{{route('sub-category.edit',$item->id)}}" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i></a>
                                        </td>
                                    </tr>
                                    @endforeach

                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>
        </div>
    </section>
</div> --}}
@endsection



@push('custom-script')

    <!-- DataTables  & Plugins -->
    <script src="{{asset('backend/plugins/datatables/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('backend/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
    <script src="{{asset('backend/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
    <script src="{{asset('backend/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
    <script src="{{asset('backend/plugins/sweetalert2/sweetalert2.min.js')}}"></script>
    <script src="{{asset('backend/plugins/toastr/toastr.min.js')}}"></script>

    <script>
        var Toast = Swal.mixin({
        toast: true,
        position: 'top-end',
        showConfirmButton: false,
        timer: 3000
        });
        $(function () {
            // if('{{Session::has('message')}}')
            // {
            //     toastr.success('{{Session::has('message')}}');
            // }
            $("#example1").DataTable();
            $("#example2").DataTable();

        });
    </script>
    
@endpush