routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Exports\ProductsExport;
use App\Exports\OrdersExport;
use App\Exports\ProductUnitExport;
use App\Exports\ProductSubCategoryExport;
use Maatwebsite\Excel\Facades\Excel;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',function(){
    return view("site.home");
});
Route::get('/about-us',function(){
    return view("site.about");
});
Route::get('/privacy-policy',function(){
    return view("site.privacy_policy");
});
Route::get('/terms-and-conditions',function(){
    return view("site.terms_and_conditions");
});

Route::get('/login',"Admin\AuthController@loginShow")->name('admin.login')->middleware('guest:admin');
Route::post('/login',"Admin\AuthController@loginPost")->name('admin.login.store');
Route::get('/logout',"Admin\AuthController@logout")->name('admin.logout')->middleware('auth:admin');

Route::middleware('auth:admin')->group(function () {
    
    Route::get('orders',"Admin\OrderController@index")->name('orders.index');
    Route::get('orders/{id}/{notifyId?}',"Admin\OrderController@detail")->name('orders.detail');
    Route::get('home',"Admin\HomeController@index")->name('home');
    Route::post('AjaxCallForAssignRider', 'Admin\OrderController@AjaxCallForAssignRider')->name('AjaxCallForAssignRider');
    Route::get('ajax-notifications', 'Admin\AjaxController@notificationAlert')->name('AjaxNotificationAlert');

    Route::post('/passwordchange','Admin\AuthController@changePassword')->name('change.password');

    //check if user type is equal to admin or not
    Route::middleware('isadmin')->group(function () {
        
        
        Route::resource('productunit',"Admin\ProductUnitController");
        Route::resource('category',"Admin\ProductCategoryController",['except' => ['destroy', 'show']]);
        Route::resource('products',"Admin\ProductsController",['except' => ['destroy', 'show']]);
        Route::resource('riders', "Admin\RiderController");
        Route::resource('customers', "Admin\CustomerController");
        Route::resource('bundles', "Admin\BundleController");

        Route::resource('sub-category', "Admin\ProductSubCategoryController");
        

        Route::post('AjaxCallForBundleProductDelete','Admin\AjaxController@AjaxCallForBundleProductDelete')->name('AjaxCallForBundleProductDelete');
        Route::post('AjaxCallForViewBundle','Admin\AjaxController@AjaxCallForViewBundle')->name('AjaxCallForViewBundle');
        Route::post('AjaxCallForViewProduct','Admin\AjaxController@AjaxCallForViewProduct')->name('AjaxCallForViewProduct');

        
        Route::post('import/products',"Admin\ProductsController@importProducts")->name('import.products');

        Route::get('export/products',function(){
            $filename = "products list ".date('Y_m_d').".xlsx";
            return Excel::download(new ProductsExport, $filename);
        })->name('export.products');
        
        
        Route::get('export/orders',function(){
            $filename = "orders list ".date('Y_m_d').".xlsx";
            return Excel::download(new OrdersExport, $filename);
        })->name('export.orders');

        Route::get('export/product-unit',function(){
            $filename = "product units ".date('Y_m_d').".xlsx";
            return Excel::download(new ProductUnitExport, $filename);
        })->name('export.product-unit');

        Route::get('export/product-subcategory',function(){
            $filename = "product-subcategory ".date('Y_m_d').".xlsx";
            return Excel::download(new ProductSubCategoryExport, $filename);
        })->name('export.product-subcategory');

        Route::get('remove-product-image/{id}','Admin\AjaxController@RemoveProductImage')->name('RemoveProductImage');
        Route::post('add-product-images','Admin\AjaxController@AddProductImages')->name('AddProductImages');
    });
});

app/Models/Bundle.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;

class Bundle extends Model implements TranslatableContract
{
    use Translatable;
    protected $fillable = ['discount_percent','active','image_name'];
    public $translatedAttributes = ['name','description'];

    public function getImagePathAttribute()
    {
        return asset("/images/bundles/{$this->image_name}");
    }

    public function bundleDetails()
    {
        return $this->hasMany('App\Models\BundleDetail','bundle_id');
    }
    public function orderDetails()
    {
        return $this->hasMany('App\Models\OrderDetail','product_id')->where('product_type',"bundles");
    }

}

app/Http/Controllers/Admin/BundleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Bundle;
use App\Models\BundleDetail;
use App\Models\Product;
use DB;
use Str;
use File;
use Image;

class BundleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected function index()
    {
        $bundles = Bundle::all();
        // dd($bundles);
        return view('admin.bundles.index',compact('bundles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $products = Product::query()->where("active",1)->get();
        return view('admin.bundles.create',compact('products'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'bundle_name_en' =>'required',
            'bundle_name_ur' =>'required',
            'bundle_description_en' => 'required',
            'bundle_description_ur' => 'required',
            'discount_percent' => 'required|numeric|min:0|max:100',
            'product.*' => 'required|distinct',
            'quantity.*' => 'required',
            'bundle_image' => 'required|image|max:2048',
        ],[
            'product.*.required' => 'The product field is required',
            'product.*.distinct' => 'The product is added to many time in table.',
            'quantity.*.required' => 'The quantity field is required',
        ]);
        $imageName = Str::random(5).'_'.time().'.'.$request->bundle_image->extension();

        DB::transaction(function() use ($request,$imageName){
            $bundle_data = [
                'en' => [
                    'name'       => $request->bundle_name_en,
                    'description' => $request->bundle_description_en
                ],
                'ur' => [
                    'name'       => $request->bundle_name_ur,
                    'description' => $request->bundle_description_ur,
                ],
                "image_name"            => $imageName,
                'discount_percent' => $request->discount_percent,
                "active" => $request->has('active')?1:0,
            ];
            $bundle = Bundle::create($bundle_data);
            foreach($request->product as $key => $product_id)
            {
                $bundleDetail = new BundleDetail;
                $bundleDetail->product_id = $product_id;
                $bundleDetail->bundle_id = $bundle->id;
                $bundleDetail->quantity =  $request->quantity[$key];
                $bundleDetail->save();
            }
            Image::make($request->bundle_image->getRealPath())->resize(600,600,function($constraint){
            })->save(public_path('/images/bundles').'/'.$imageName);
        });
        return redirect()->route('bundles.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $bundles = Bundle::find($id);
        $products = Product::query()->where("active",1)->get();
        return view('admin.bundles.edit',compact('bundles','products'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // dd($request);
        $request->validate([
            'bundle_name_en'            =>'required',
            'bundle_name_ur'            =>'required',
            'bundle_description_en'     => 'required',
            'bundle_description_ur'     => 'required',
            'discount_percent'          => 'required|numeric|min:0|max:100',
            'product.*'                 => 'required|distinct',
            'quantity.*'                => 'required',
            'bundle_image'              => 'nullable|image|max:2048',

        ],[
            'product.*.required'        => 'The product field is required',
            'product.*.distinct'        => 'The product is added to many time in table.',
            'quantity.*.required'       => 'The quantity field is required',
        ]);


        DB::transaction(function() use ($request,$id){
            $bundle = Bundle::findOrFail($id);
            $bundle->translate('en')->name          = $request->bundle_name_en;
            $bundle->translate('en')->description   = $request->bundle_description_en;
            $bundle->translate('ur')->name          = $request->bundle_name_ur;
            $bundle->translate('ur')->description   = $request->bundle_description_ur;
            $bundle->discount_percent               = $request->discount_percent;
            $bundle->active                         = $request->has('active')?1:0;

            if($request->hasFile('bundle_image'))
            {
                File::delete(public_path('/images/bundles/'.$bundle->image_name));
                $imageName = Str::random(5).'_'.time().'.'.$request->bundle_image->extension();
                $request->bundle_image->move(public_path('/images/bundles'), $imageName);
                $bundle->image_name = $imageName;
            }

            $bundle->save();

            foreach($request->product as $key => $product_id)
            {
                $bundleDetail               = isset($request->bundle_detail_id[$key])? BundleDetail::find($request->bundle_detail_id[$key]):new BundleDetail;
                $bundleDetail->product_id   = $product_id;
                $bundleDetail->bundle_id    = $bundle->id;
                $bundleDetail->quantity     =  $request->quantity[$key];
                $bundleDetail->save();
            }
        });
        return redirect()->route('bundles.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/bundles/create.blade.php
@extends('admin.layouts.app')
@push('custom-css')
<link rel="stylesheet" href="{{asset('backend/plugins/select2/css/select2.min.css')}}">
<link rel="stylesheet" href="{{asset('backend/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css')}}">
<style>
    #bundleDetailTable tbody td:first-child,#bundleDetailTable tbody th:first-child{
        width: 40%;
    }
</style>
@endpush
@section('content')
<div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card card-primary mt-4">
                <div class="card-header">
                  <h3 class="card-title">Add Bundle</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form action="{{route('bundles.store')}}" method="post" enctype="multipart/form-data">
                    @csrf
                  <div class="card-body">
                      <div class="row">
                        <div class="form-group col-md-6">
                            <label for="bundle_name_en">Name (English)</label>
                            <input type="text" name="bundle_name_en" class="form-control @error('bundle_name_en') is-invalid @enderror" value="{{old('bundle_name_en')}}" id="bundle_name_en">
                            @error('bundle_name_en')
                                <p class="text-danger text-sm">{{$message}}</p>
                            @enderror
                        </div>
                        <div class="form-group col-md-6">
                            <label for="bundle_name_ur">Name (اردو)</label>
                            <input type="text" name="bundle_name_ur" class="form-control @error('bundle_name_ur') is-invalid @enderror" value="{{old('bundle_name_ur')}}" id="bundle_name_ur">
                            @error('bundle_name_ur')
                                <p class="text-danger text-sm">{{$message}}</p>
                            @enderror
                        </div>
                        
                        <div class="form-group col-md-6">
                            <label for="bundle_description_en">Bundle Description (English)</label>
                            <textarea name="bundle_description_en" id="" class="form-control @error('bundle_description_en') is-invalid @enderror" rows="5">{{old('bundle_description_en')}}</textarea>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="bundle_description_ur">Bundle Description (اردو)</label>
                            <textarea name="bundle_description_ur" id="" class="form-control @error('bundle_description_ur') is-invalid @enderror" rows="5">{{old('bundle_description_ur')}}</textarea>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="discount_percent">Discount Percentage</label>
                            <input type="number" name="discount_percent" class="form-control @error('discount_percent') is-invalid @enderror" value="{{old('discount_percent')}}" id="discount_percent">
                            @error('discount_percent')
                                <p class="text-danger text-sm">{{$message}}</p>
                            @enderror
                        </div>
                        <div class="form-group col-md-6">
                            <div class="row">
                                <div class="col-md-6 col-lg-8">
                                    <label for="bundle_image">Bundle Image</label>
                                    <input type="file" accept="image/*" class="form-control-file @error('bundle_image') is-invalid @enderror" name="bundle_image" id="bundle_image">
                                    @error('bundle_image')
                                        <p class="text-danger text-sm">{{$message}}</p>
                                    @enderror
                                </div>
                                <div class="col-md-6 col-lg-4">
                                    <img src="" height="80" width="auto" alt="" id="bundleImage" srcset="" class="float-right mr-5">
                                </div>
                            </div>
                            
                        </div>
                        <div class="form-group col-12">
                            <div class="form-check d-inline-block">
                                <input type="checkbox" class="form-check-input" value="1" name="active" id="active" checked>
                                <label class="form-check-label" for="active">Active</label>
                            </div>
                            <button type="button" class="btn btn-success btn-sm float-right" id="btnAddProduct">Add Product</button>
                        </div>
                        <div class="col-12">
                            <div class="table-responsive">
                            <table class="table table-bordered" id="bundleDetailTable">
                                <thead>
                                    <tr>
                                        <th>Select Product</th>
                                        <th>Quantity</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (old('product') != null)
                                            @foreach (old('product') as $key => $oldValues)
                                            <tr>
                                                <td>
                                                    <div class="form-group">
                                                        <select name="product[]" id="" class="form-control select2 @error('product.'.$key) is-invalid @enderror">
                                                            <option value>Select Product</option>
                                                            @foreach ($products as $item)
                                                                <option value="{{$item->id}}" {{old('product.'.$key) == $item->id?'selected':''}}>{{$item->name}}</option>
                                                            @endforeach
                                                        </select>
                                                        @error('product.'.$key)
                                                            <span class="text-sm text-danger" style="padding: 5px;font-size:12px">{{$message}}</span>
                                                        @enderror
                                                    </div>
                                                    
                                                </td>
                                                <td>
                                                    <div class="form-group">
                                                        <input type="number" class="form-control @error('quantity.'.$key) is-invalid @enderror" name="quantity[]" placeholder="Enter Quantity" value="{{old('quantity.'.$key)}}">
                                                        @error('quantity.'.$key)
                                                            <span class="text-sm text-danger" style="padding: 5px;font-size:12px">{{$message}}</span>
                                                        @enderror
                                                    </div>
                                                    
                                                </td>
                                                <td>
                                                    @if ($key != 0)
                                                    <button class="btn btn-danger btn-sm btnRowDelete"><i class="fa fa-trash"></i></button>
                                                    @endif
                                                </td>
                                            </tr>
                                            @endforeach
                                    @else
                                        <tr>
                                            <td>
                                                <div class="form-group">
                                                    <select name="product[]" id="" class="form-control select2">
                                                        <option value>Select Product</option>
                                                        @foreach ($products as $item)
                                                            <option value="{{$item->id}}">{{$item->name}}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="form-group">
                                                    <input type="number" class="form-control" name="quantity[]" placeholder="Enter Quantity">
                                                </div>
                                            </td>
                                            <td></td>
                                        </tr>
                                    @endif
                                    
                                </tbody>
                            </table>
                            </div>
                        </div>
                      </div>
                  </div>
                  <!-- /.card-body -->
                  <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a href="{{route('bundles.index')}}" class="btn btn-default">Back</a>

                  </div>
                </form>
              </div>
            
          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <script type="text/html" id="data-row">
    <tr>
        <td>
            <div class="form-group">
                <select name="product[]" id="" class="form-control select2detail">
                    <option value>Select Product</option>
                    @foreach ($products as $item)
                        <option value="{{$item->id}}">{{$item->name}}</option>
                    @endforeach
                </select>
            </div>
        </td>
        <td>
            <div class="form-group">
                <input type="number" class="form-control" name="quantity[]" placeholder="Enter Quantity">
            </div>
        </td>
        <td>
            <button class="btn btn-danger btn-sm btnRowDelete"><i class="fa fa-trash"></i></button>
        </td>
    </script>
@endsection
@push('custom-script')
<script src="{{asset('backend/plugins/select2/js/select2.full.min.js')}}"></script>
    <script>
        var fileInput = document.querySelector("#bundle_image")
        var ImageElement = document.querySelector("#bundleImage")
        
        fileInput.addEventListener("change",function(){
            if (fileInput.files && fileInput.files[0]) {
            var reader = new FileReader();
            reader.onload = function(e) {
                ImageElement.setAttribute("src", e.target.result);
            }
            reader.readAsDataURL(fileInput.files[0]); // convert to base64 string
            }
        })
        jQuery(document).ready(function(){
            $('.select2').select2({
                theme: 'bootstrap4'
            })
        })
        $(document).on('click','#btnAddProduct',function(){
            $('#bundleDetailTable').find('tbody').append($('#data-row').html());
            $('.select2detail').select2({
                theme: 'bootstrap4'
            })
        });
        $(document).on('click','.btnRowDelete',function(){
            $(this).parents('tr').remove();
        });
    </script>
@endpush

resources/views/admin/bundles/modal.blade.php
<div class="row">
    <div class="col-md-6">

        <div class="form-group">
            <label>Bundle Image:</label><br>
            <img src="{{$bundle->image_path}}" height="200" width="auto" alt="" srcset="">
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <label>Discount Percentage %:</label>
            <p>{{$bundle->discount_percent}}</p>

            <label>Status:</label>
            <p>{{(($bundle->active==1)? 'Active':'Deactive')}}</p>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">

        <div class="form-group">
            <label>Name (English):</label>
            <p>{{$bundle->translate('en')->name}}</p>
            <label>Description (English):</label><br>
            <p>{{$bundle->translate('en')->description}}</p>
            
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group ">
            <label>Name (اردو):</label>
            <p>{{$bundle->translate('ur')->name}}</p>

            <label>Description (اردو):</label><br>
            <p>{{$bundle->translate('ur')->description}}</p>
        </div>

        

    </div>
    
</div>

<hr>
<div class="row">
    <div class="form-group col-md-12">
        <h4 style="text-align:center"> Product Detail </h4>
    </div>
</div>

@php

$i = 1;
$amount = 0;

@endphp

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Product</th>
            <th>Quantity</th>
        </tr>
    </thead>
    <tbody>

        @foreach ($bundle->bundleDetails as $val)

        <tr>
            <td>{{$val->product->translate('en')->name}}</td>
            <td>{{$val->quantity}}</td>
        </tr>

        @php
        $amount += ($val->quantity * $val->product->discount_price);
        @endphp

        @endforeach

    </tbody>
</table>

@php
$discount_amount = $amount - ($amount * ($bundle->discount_percent / 100));
@endphp
{{-- // original_price - (original_price * discount / 100) --}}

<div class="row">
    <div class="form-group col-md-12">
        <h4 style="text-align:right"> Total Amount : {{$amount}} </h4>
    </div>
</div>
<div class="row">
    <div class="form-group col-md-12">
        <h4 style="text-align:right"> Total Discount Amount : {{round($discount_amount)}} </h4>
    </div>
</div>