routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Exports\ProductsExport;
use App\Exports\OrdersExport;
use App\Exports\ProductUnitExport;
use App\Exports\ProductSubCategoryExport;
use Maatwebsite\Excel\Facades\Excel;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',function(){
    return view("site.home");
});
Route::get('/about-us',function(){
    return view("site.about");
});
Route::get('/privacy-policy',function(){
    return view("site.privacy_policy");
});
Route::get('/terms-and-conditions',function(){
    return view("site.terms_and_conditions");
});

Route::get('/login',"Admin\AuthController@loginShow")->name('admin.login')->middleware('guest:admin');
Route::post('/login',"Admin\AuthController@loginPost")->name('admin.login.store');
Route::get('/logout',"Admin\AuthController@logout")->name('admin.logout')->middleware('auth:admin');

Route::middleware('auth:admin')->group(function () {
    
    Route::get('orders',"Admin\OrderController@index")->name('orders.index');
    Route::get('orders/{id}/{notifyId?}',"Admin\OrderController@detail")->name('orders.detail');
    Route::get('home',"Admin\HomeController@index")->name('home');
    Route::post('AjaxCallForAssignRider', 'Admin\OrderController@AjaxCallForAssignRider')->name('AjaxCallForAssignRider');
    Route::get('ajax-notifications', 'Admin\AjaxController@notificationAlert')->name('AjaxNotificationAlert');

    Route::post('/passwordchange','Admin\AuthController@changePassword')->name('change.password');

    //check if user type is equal to admin or not
    Route::middleware('isadmin')->group(function () {
        
        
        Route::resource('productunit',"Admin\ProductUnitController");
        Route::resource('category',"Admin\ProductCategoryController",['except' => ['destroy', 'show']]);
        Route::resource('products',"Admin\ProductsController",['except' => ['destroy', 'show']]);
        Route::resource('riders', "Admin\RiderController");
        Route::resource('customers', "Admin\CustomerController");
        Route::resource('bundles', "Admin\BundleController");

        Route::resource('sub-category', "Admin\ProductSubCategoryController");
        

        Route::post('AjaxCallForBundleProductDelete','Admin\AjaxController@AjaxCallForBundleProductDelete')->name('AjaxCallForBundleProductDelete');
        Route::post('AjaxCallForViewBundle','Admin\AjaxController@AjaxCallForViewBundle')->name('AjaxCallForViewBundle');
        Route::post('AjaxCallForViewProduct','Admin\AjaxController@AjaxCallForViewProduct')->name('AjaxCallForViewProduct');

        
        Route::post('import/products',"Admin\ProductsController@importProducts")->name('import.products');

        Route::get('export/products',function(){
            $filename = "products list ".date('Y_m_d').".xlsx";
            return Excel::download(new ProductsExport, $filename);
        })->name('export.products');
        
        
        Route::get('export/orders',function(){
            $filename = "orders list ".date('Y_m_d').".xlsx";
            return Excel::download(new OrdersExport, $filename);
        })->name('export.orders');

        Route::get('export/product-unit',function(){
            $filename = "product units ".date('Y_m_d').".xlsx";
            return Excel::download(new ProductUnitExport, $filename);
        })->name('export.product-unit');

        Route::get('export/product-subcategory',function(){
            $filename = "product-subcategory ".date('Y_m_d').".xlsx";
            return Excel::download(new ProductSubCategoryExport, $filename);
        })->name('export.product-subcategory');

        Route::get('remove-product-image/{id}','Admin\AjaxController@RemoveProductImage')->name('RemoveProductImage');
        Route::post('add-product-images','Admin\AjaxController@AddProductImages')->name('AddProductImages');
    });
});

resources/views/admin/partials/aside.blade.php
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{{route('home')}}" class="brand-link">
        <img src="{{asset('backend/dist/img/AdminLTELogo.png')}}" alt="AdminLTE Logo"
            class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">KIOSK</span>
    </a>
    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{asset('backend/dist/img/avatar5.png')}}" class="img-circle elevation-2"
                    alt="User Image">
            </div>
            <div class="info">
                <a href="{{route('home')}}" class="d-block">{{Auth::user()->name}}</a>
            </div>
        </div>
        <!-- SidebarSearch Form -->
        {{-- <div class="form-inline">
     <div class="input-group" data-widget="sidebar-search">
       <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
       <div class="input-group-append">
         <button class="btn btn-sidebar">
           <i class="fas fa-search fa-fw"></i>
         </button>
       </div>
     </div>
   </div> --}}
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
            with font-awesome or any other icon font library -->
            <li class="nav-item">
                <a href="{{route('orders.index')}}" class="nav-link">
                    {{-- <i class="nav-icon fas fa-tree"></i> --}}
                    <i class="nav-icon fas fa-box"></i>
                    <p>
                        Orders
                    </p>
                </a>
            </li>
                @if (Auth::user()->user_type === "admin")
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        {{-- <i class="nav-icon fas fa-chart-pie"></i> --}}
                        <i class="nav-icon fas fa-balance-scale"></i>
                        <p>
                            Product Unit
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{route('productunit.create')}}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Add Unit</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{route('productunit.index')}}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>View Unit</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        {{-- <i class="nav-icon fas fa-chart-pie"></i> --}}
                        <i class="nav-icon fas fa-code-branch"></i>
                        <p>
                            Product Category
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{route('category.create')}}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Add Category</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{route('category.index')}}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>View Category</p>
                            </a>
                        </li>
                        
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="fas fa-box-open"></i>
                        <p>
                            Product Sub Category
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        
                        <li class="nav-item">
                            <a href="{{route('sub-category.create')}}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Add Sub Category</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{route('sub-category.index')}}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>View Sub Category</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fab fa-raspberry-pi"></i>
                        <p>
                            Products
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{route('products.create')}}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Add Product</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{route('products.index')}}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>View Products</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-box"></i>
                        <p>
                            Bundles
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{route('bundles.create')}}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Add Bundle</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{route('bundles.index')}}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>View Bundles</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        {{-- <i class="nav-icon fas fa-chart-pie"></i> --}}
                        <i class="nav-icon fas fa-motorcycle"></i>
                        <p>
                            Riders
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{route('riders.create')}}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Add Rider</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{route('riders.index')}}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>View Riders</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="{{route('customers.index')}}" class="nav-link">
                        {{-- <i class="nav-icon fas fa-tree"></i> --}}
                        <i class="nav-icon fas fa-users"></i>
                        <p>
                            Customers
                        </p>
                    </a>
                </li>
                @endif
                
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

resources/views/admin/partials/changePassword.blade.php
<div class="modal fade" id="changePasswordModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Change Password</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="alert bg-danger text-light pb-0" id="changePassError" style="display: none">
          </div>
          <form action="" method="post" id="changePassword">
            <div class="form-group">
              <label for="">Old Password</label>
              <input type="password" name="oldpassword" id="oldpassword" class="form-control">
            </div>
            <div class="form-group">
              <label for="">New Password</label>
              <input type="password" name="newpassword" id="newpassword" class="form-control">
            </div>
            <div class="form-group">
              <label for="">Confirm Password</label>
              <input type="password" name="newpassword_confirmation" id="newpassword_confirmation" class="form-control">
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" id="btnsubmitPassChange" class="btn btn-primary" form="changePassword">Change Password</button>
        </div>
      </div>
    </div>
  </div>

resources/views/admin/partials/notification.blade.php
@if(count($notifications) > 0)
@foreach ($notifications as $item)
<a href="{{$item->data["order_detail_link"]."/".$item->id}}" class="dropdown-item">
    <i class="fa fa-first-order" aria-hidden="true"></i> New Order Recieved
    <span class="float-right text-muted text-sm">Order #: {{$item->data["order_id"]}}</span>
  </a>
<div class="dropdown-divider"></div>
@endforeach
@else
    <p class="text-center p-3">No new order found.</p>
@endif

resources/views/admin/partials/script.blade.php
<!-- jQuery -->
<script src="{{asset('backend/plugins/jquery/jquery.min.js')}}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{asset('backend/plugins/jquery-ui/jquery-ui.min.js')}}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{{asset('backend/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
{{-- <!-- ChartJS -->
<script src="{{asset('backend/plugins/chart.js/Chart.min.js')}}"></script>
<!-- Sparkline -->
<script src="{{asset('backend/plugins/sparklines/sparkline.js')}}"></script>
<!-- JQVMap -->
<script src="{{asset('backend/plugins/jqvmap/jquery.vmap.min.js')}}"></script>
<script src="{{asset('backend/plugins/jqvmap/maps/jquery.vmap.usa.js')}}"></script> --}}
<!-- jQuery Knob Chart -->
<script src="{{asset('backend/plugins/jquery-knob/jquery.knob.min.js')}}"></script>
<!-- daterangepicker -->
<script src="{{asset('backend/plugins/moment/moment.min.js')}}"></script>
<script src="{{asset('backend/plugins/daterangepicker/daterangepicker.js')}}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{asset('backend/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js')}}"></script>
<!-- Summernote -->
<script src="{{asset('backend/plugins/summernote/summernote-bs4.min.js')}}"></script>
<!-- overlayScrollbars -->
<script src="{{asset('backend/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('backend/dist/js/adminlte.js')}}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{asset('backend/dist/js/demo.js')}}"></script>
<script src="{{asset('backend/plugins/toastr/toastr.min.js')}}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
{{-- <script src="{{asset('backend/dist/js/pages/dashboard.js')}}"></script> --}}
<script>
  $.ajaxSetup({
  headers: {
      'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
  }
});
function changePasswordErrorMsg(msg,container) {
      $(container).html('<ul style="list-style:none" class="pl-0"></ul>');
      $(container).css('display','block');
      $.each( msg, function( key, value ) {
         $(container).find("ul").append('<li>'+value+'</li>');
      });
   }
   //CHANGE Password modal Open
$(document).on('click','#btnChangePassword',function(){
      $('#newpassword_confirmation').val('');
      $('#newpassword').val('');
      $('#oldpassword').val('');
      $('#changePassError').css('display','none');
      $('#changePasswordModal').modal('show');
});

    //Change Password Ajax Request  
    $('#changePassword').submit(function(e){
      e.preventDefault();
      $.ajax({
        url: "{{route('change.password')}}",
        type: "POST",
        data:  new FormData(this),
        contentType: false,
        cache: false,
        processData:false,
        dataType:'JSON',
        beforeSend : function()
        {
          $('#btnsubmitPassChange').prop('disabled',true);
        },
        success: function(data)
        {
            if($.isEmptyObject(data.error)){
                if(data.status)
                {
                  $('#changePasswordModal').modal('hide');
                  toastr.options = {
                    "closeButton": true
                  }
                  toastr["success"]("Password Changed Successfully")
                }
            }else{
                changePasswordErrorMsg(data.error,"#changePassError");
            }
        }, error:function(jhxr,status,err){
            console.log(jhxr);
        },
        complete:function(){
          $('#btnsubmitPassChange').prop('disabled',false);
        }   
        });
    })
    //Ajax call to get notification
    function getNotifications()
    {
      $.getJSON('{{route("AjaxNotificationAlert")}}',function(data){
        $('#notification-count').text((data.new_notification_count > 0?data.new_notification_count:""));
        $('#notification-body').html(data.notifications);
      })
    }
    //onload Call
    getNotifications()
    //GET Notifications after 5 secs Interval Reload
    setInterval(getNotifications, 5000);
</script>
@stack('custom-script')

resources/views/admin/partials/style.blade.php
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{asset('backend/plugins/fontawesome-free/css/all.min.css')}}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="{{asset('backend/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css')}}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{{asset('backend/plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}">
  <!-- JQVMap -->
  {{-- <link rel="stylesheet" href="{{asset('backend/plugins/jqvmap/jqvmap.min.css')}}"> --}}
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('backend/dist/css/adminlte.min.css')}}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{{asset('backend/plugins/overlayScrollbars/css/OverlayScrollbars.min.css')}}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{{asset('backend/plugins/daterangepicker/daterangepicker.css')}}">
  <!-- summernote -->
  <link rel="stylesheet" href="{{asset('backend/plugins/summernote/summernote-bs4.min.css')}}">
  <link rel="stylesheet" href="{{asset('backend/plugins/toastr/toastr.min.css')}}">
  @stack('custom-css')